index :
    number_of_shards : 1
    number_of_replicas : 0
analysis :
  analyzer :
    trim_lowercase :
      tokenizer : keyword
      filter :
        - trim
        - lowercase
    standard :
      tokenizer : standard
      filter :
        - lowercase
        - standard